[package]
name = "gui-druid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atk = "0.16.0"
atk-sys = "0.16.0"
druid = "0.7.0"
pango = "0.16.5"
